name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      id: send_greeting
      run: echo "Hello ${{ inputs.name }}" > greeting.txt

    - name: Upload greeting as artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: greeting-artifact
        path: greeting.txt

  greet2:
    name: Greet in dev environment with input ${{ inputs.name }}
    needs: [greet]
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://github.com/${{ github.repository }}

    steps:
    - name: Download greeting artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: greeting-artifact

    - name: Print greeting from artifact
      run: cat greeting.txt

  greet3:
    name: Greet in staging environment with input ${{ inputs.name }}
    needs: [greet]
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://github.com/${{ github.repository }}

    steps:
    - name: Download greeting artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: greeting-artifact

    - name: Print greeting from artifact
      run: cat greeting.txt


  cache-example:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache pip packages
      uses: actions/cache@v4.0.2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt
